import { v4 as uuid } from 'uuid';
import type { CVData, CVSection } from '@/types/cv';

/**
 * Parse an HTML string back into CVData sections.
 * This is a best-effort parser that works with the HTML generated by generateHTML.
 */
export function parseHTMLToCV(html: string, existingCV: CVData): CVData {
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');
  const body = doc.body;
  const sections: CVSection[] = [];

  const children = Array.from(body.children);

  for (const el of children) {
    const tag = el.tagName.toLowerCase();

    if (tag === 'header') {
      const h1 = el.querySelector('h1');
      const paragraphs = Array.from(el.querySelectorAll('p'));
      const fullName = h1?.textContent || 'Your Name';
      const jobTitle = paragraphs[0]?.textContent || '';
      const contactLine = paragraphs[1]?.textContent || '';
      const contactParts = contactLine.split('|').map(s => s.trim());
      const extraLine = paragraphs[2]?.textContent || '';
      const extraParts = extraLine.split('|').map(s => s.trim());

      sections.push({
        id: uuid(),
        type: 'personal-info',
        title: 'Personal Info',
        content: {
          fullName,
          jobTitle,
          email: contactParts[0] || '',
          phone: contactParts[1] || '',
          location: contactParts[2] || '',
          linkedin: extraParts[0] || '',
          website: extraParts[1] || '',
        },
      });
    } else if (tag === 'section') {
      const h2 = el.querySelector('h2');
      const title = h2?.textContent || '';
      const titleLower = title.toLowerCase();

      if (titleLower.includes('summary') || titleLower.includes('profile') || titleLower.includes('objective')) {
        const p = el.querySelector('p');
        sections.push({
          id: uuid(), type: 'summary', title,
          content: { text: p?.textContent || '' },
        });
      } else if (titleLower.includes('experience') || titleLower.includes('work')) {
        const divs = Array.from(el.querySelectorAll(':scope > div'));
        const items = divs.map(div => {
          const h3 = div.querySelector('h3');
          const p = div.querySelector('p');
          const lis = Array.from(div.querySelectorAll('li'));
          const h3Text = h3?.textContent || '';
          const [rolePart, ...compParts] = h3Text.split('—').map(s => s.trim());
          const dateText = p?.textContent || '';
          const [start, ...endParts] = dateText.split('–').map(s => s.trim());
          return {
            id: uuid(),
            role: rolePart,
            company: compParts.join(' — '),
            startDate: start,
            endDate: endParts.join(' – '),
            bullets: lis.map(li => li.textContent || ''),
          };
        });
        sections.push({ id: uuid(), type: 'experience', title, content: { items } });
      } else if (titleLower.includes('education')) {
        const divs = Array.from(el.querySelectorAll(':scope > div'));
        const items = divs.map(div => {
          const h3 = div.querySelector('h3');
          const ps = Array.from(div.querySelectorAll('p'));
          const h3Text = h3?.textContent || '';
          const [deg, ...instParts] = h3Text.split('—').map(s => s.trim());
          const dateText = ps[0]?.textContent || '';
          const [start, ...endParts] = dateText.split('–').map(s => s.trim());
          return {
            id: uuid(),
            degree: deg,
            institution: instParts.join(' — '),
            startDate: start,
            endDate: endParts.join(' – '),
            details: ps[1]?.textContent || undefined,
          };
        });
        sections.push({ id: uuid(), type: 'education', title, content: { items } });
      } else if (titleLower.includes('skill')) {
        const ps = Array.from(el.querySelectorAll('p'));
        const categories = ps.map(p => {
          const strong = p.querySelector('strong');
          const name = (strong?.textContent || '').replace(':', '').trim();
          const skillsText = (p.textContent || '').replace(strong?.textContent || '', '').trim();
          return { id: uuid(), name, skills: skillsText.split(',').map(s => s.trim()).filter(Boolean) };
        });
        sections.push({ id: uuid(), type: 'skills', title, content: { categories } });
      } else if (titleLower.includes('project')) {
        const divs = Array.from(el.querySelectorAll(':scope > div'));
        const items = divs.map(div => {
          const h3 = div.querySelector('h3');
          const ps = Array.from(div.querySelectorAll('p'));
          const em = div.querySelector('em');
          return {
            id: uuid(),
            name: h3?.textContent || '',
            description: ps[0]?.textContent || '',
            technologies: em?.textContent || ps[1]?.textContent || '',
          };
        });
        sections.push({ id: uuid(), type: 'projects', title, content: { items } });
      } else if (titleLower.includes('certif')) {
        const lis = Array.from(el.querySelectorAll('li'));
        const items = lis.map(li => {
          const text = li.textContent || '';
          const match = text.match(/^(.+?)\s*—\s*(.+?)\s*\((.+?)\)$/);
          return {
            id: uuid(),
            name: match?.[1] || text,
            issuer: match?.[2] || '',
            date: match?.[3] || '',
          };
        });
        sections.push({ id: uuid(), type: 'certifications', title, content: { items } });
      } else if (titleLower.includes('language')) {
        const lis = Array.from(el.querySelectorAll('li'));
        const items = lis.map(li => {
          const text = li.textContent || '';
          const [lang, ...prof] = text.split('—').map(s => s.trim());
          return { id: uuid(), language: lang, proficiency: prof.join(' — ') };
        });
        sections.push({ id: uuid(), type: 'languages', title, content: { items } });
      } else {
        // Treat as custom
        sections.push({ id: uuid(), type: 'custom', title, content: { html: el.innerHTML } });
      }
    } else if (tag === 'div') {
      // Spacer
      const height = parseInt((el as HTMLElement).style.height) || 24;
      sections.push({ id: uuid(), type: 'spacer', title: 'Spacer', content: { height } });
    }
  }

  return {
    ...existingCV,
    sections: sections.length > 0 ? sections : existingCV.sections,
    updatedAt: new Date().toISOString(),
  };
}
